server:
  port: 8080
spring:
  application:
    name: "Products"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://localhost:3306/products_db
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
